//go:build !noasm && arm64
// Code generated by gocc -- DO NOT EDIT.

package streamvbyte


//go:noescape
func svb_encode_u32(in []uint32, out *byte, scheme byte) uint64

//go:noescape
func svb_encode_s32(in []int32, out *byte, scheme byte) int64

//go:noescape
func svb_decode_u32(in []byte, count int, out *uint32, scheme byte) uint64

//go:noescape
func svb_decode_s32(in []byte, count int, out *int32, scheme byte) uint64

//go:noescape
func svb_delta_encode_u32(in []uint32, prev uint32, out *byte, scheme byte) uint64

//go:noescape
func svb_delta_encode_s32(in []int32, prev int32, out *byte, scheme byte) uint64

//go:noescape
func svb_delta_decode_u32(in []byte, count int, prev uint32, out *uint32, scheme byte) uint64

//go:noescape
func svb_delta_decode_s32(in []byte, count int, prev int32, out *int32, scheme byte) uint64
