//go:build !noasm && arm64
// Code generated by gocc -- DO NOT EDIT.

package streamvbyte


//go:noescape
func svb_decode(in []byte, count int, out *uint32) uint64

//go:noescape
func svb_delta_decode(in []byte, count int, prev uint32, out *uint32) uint64
