//go:build !noasm && amd64
// Code generated by gocc v0.16.5-rev-57c4d32 -- DO NOT EDIT.
//
// Source file         : zigzag.c
// Clang version       : Apple clang version 17.0.0 (clang-1700.6.4.2)
// Target architecture : amd64
// Compiler options    : [none]

#include "textflag.h"

TEXT ·zigzag_encode_sse(SB), NOSPLIT, $0-24
	MOVQ in+0(FP), DI
	MOVQ out+8(FP), SI
	MOVQ N+16(FP), DX
	NOP                      // (skipped)                            // push	rbp
	NOP                      // (skipped)                            // mov	rbp, rsp
	NOP                      // (skipped)                            // and	rsp, -8
	WORD $0x8548; BYTE $0xd2 // TESTQ DX, DX                         // test	rdx, rdx
	JE   LBB0_10             // <--                                  // je	.LBB0_10
	CMPQ DX, $0x8            // <--                                  // cmp	rdx, 8
	WORD $0x930f; BYTE $0xc0 // SETAE AL                             // setae	al
	MOVQ SI, CX              // <--                                  // mov	rcx, rsi
	SUBQ DI, CX              // <--                                  // sub	rcx, rdi
	CMPQ CX, $0x20           // <--                                  // cmp	rcx, 32
	WORD $0x930f; BYTE $0xc1 // SETAE CL                             // setae	cl
	WORD $0xc884             // TESTL CL, AL                         // test	al, cl
	JNE  LBB0_7              // <--                                  // jne	.LBB0_7
	XORL AX, AX              // <--                                  // xor	eax, eax
	JMP  LBB0_3              // <--                                  // jmp	.LBB0_3

LBB0_7:
	MOVQ DX, AX    // <--                                  // mov	rax, rdx
	ANDQ $-0x8, AX // <--                                  // and	rax, -8
	XORL CX, CX    // <--                                  // xor	ecx, ecx

LBB0_8:
	LONG $0x046f0ff3; BYTE $0x8f   // MOVDQU 0(DI)(CX*4), X0               // movdqu	xmm0, xmmword ptr [rdi + 4*rcx]
	LONG $0x4c6f0ff3; WORD $0x108f // MOVDQU 0x10(DI)(CX*4), X1            // movdqu	xmm1, xmmword ptr [rdi + 4*rcx + 16]
	LONG $0xd06f0f66               // MOVDQA X0, X2                        // movdqa	xmm2, xmm0
	LONG $0xd0fe0f66               // PADDD X0, X2                         // paddd	xmm2, xmm0
	LONG $0xd96f0f66               // MOVDQA X1, X3                        // movdqa	xmm3, xmm1
	LONG $0xd9fe0f66               // PADDD X1, X3                         // paddd	xmm3, xmm1
	LONG $0xe0720f66; BYTE $0x1f   // PSRAD $0x1f, X0                      // psrad	xmm0, 31
	LONG $0xc2ef0f66               // PXOR X2, X0                          // pxor	xmm0, xmm2
	LONG $0xe1720f66; BYTE $0x1f   // PSRAD $0x1f, X1                      // psrad	xmm1, 31
	LONG $0xcbef0f66               // PXOR X3, X1                          // pxor	xmm1, xmm3
	LONG $0x047f0ff3; BYTE $0x8e   // MOVDQU X0, 0(SI)(CX*4)               // movdqu	xmmword ptr [rsi + 4*rcx], xmm0
	LONG $0x4c7f0ff3; WORD $0x108e // MOVDQU X1, 0x10(SI)(CX*4)            // movdqu	xmmword ptr [rsi + 4*rcx + 16], xmm1
	ADDQ $0x8, CX                  // <--                                  // add	rcx, 8
	CMPQ AX, CX                    // <--                                  // cmp	rax, rcx
	JNE  LBB0_8                    // <--                                  // jne	.LBB0_8
	CMPQ AX, DX                    // <--                                  // cmp	rax, rdx
	JE   LBB0_10                   // <--                                  // je	.LBB0_10

LBB0_3:
	MOVQ AX, CX              // <--                                  // mov	rcx, rax
	WORD $0xc2f6; BYTE $0x01 // TESTL $0x1, DL                       // test	dl, 1
	JE   LBB0_5              // <--                                  // je	.LBB0_5
	WORD $0x0c8b; BYTE $0x87 // MOVL 0(DI)(AX*4), CX                 // mov	ecx, dword ptr [rdi + 4*rax]
	LONG $0x09048d44         // LEAL 0(CX)(CX*1), R8                 // lea	r8d, [rcx + rcx]
	WORD $0xf9c1; BYTE $0x1f // SARL $0x1f, CX                       // sar	ecx, 31
	XORL R8, CX              // <--                                  // xor	ecx, r8d
	WORD $0x0c89; BYTE $0x86 // MOVL CX, 0(SI)(AX*4)                 // mov	dword ptr [rsi + 4*rax], ecx
	MOVQ AX, CX              // <--                                  // mov	rcx, rax
	ORQ  $0x1, CX            // <--                                  // or	rcx, 1

LBB0_5:
	LEAQ -0x1(DX), R8 // <--                                  // lea	r8, [rdx - 1]
	CMPQ AX, R8       // <--                                  // cmp	rax, r8
	JE   LBB0_10      // <--                                  // je	.LBB0_10

LBB0_6:
	WORD $0x048b; BYTE $0x8f // MOVL 0(DI)(CX*4), AX                 // mov	eax, dword ptr [rdi + 4*rcx]
	LONG $0x00048d44         // LEAL 0(AX)(AX*1), R8                 // lea	r8d, [rax + rax]
	WORD $0xf8c1; BYTE $0x1f // SARL $0x1f, AX                       // sar	eax, 31
	XORL R8, AX              // <--                                  // xor	eax, r8d
	WORD $0x0489; BYTE $0x8e // MOVL AX, 0(SI)(CX*4)                 // mov	dword ptr [rsi + 4*rcx], eax
	LONG $0x048f448b         // MOVL 0x4(DI)(CX*4), AX               // mov	eax, dword ptr [rdi + 4*rcx + 4]
	LONG $0x00048d44         // LEAL 0(AX)(AX*1), R8                 // lea	r8d, [rax + rax]
	WORD $0xf8c1; BYTE $0x1f // SARL $0x1f, AX                       // sar	eax, 31
	XORL R8, AX              // <--                                  // xor	eax, r8d
	LONG $0x048e4489         // MOVL AX, 0x4(SI)(CX*4)               // mov	dword ptr [rsi + 4*rcx + 4], eax
	ADDQ $0x2, CX            // <--                                  // add	rcx, 2
	CMPQ DX, CX              // <--                                  // cmp	rdx, rcx
	JNE  LBB0_6              // <--                                  // jne	.LBB0_6

LBB0_10:
	NOP // (skipped)                            // mov	rsp, rbp
	NOP // (skipped)                            // pop	rbp
	RET // <--                                  // ret

TEXT ·zigzag_delta_encode_sse(SB), NOSPLIT, $0-28
	MOVQ    in+0(FP), DI
	MOVQ    out+8(FP), SI
	MOVQ    N+16(FP), DX
	MOVLQZX prev+24(FP), CX
	NOP                         // (skipped)                            // push	rbp
	NOP                         // (skipped)                            // mov	rbp, rsp
	NOP                         // (skipped)                            // and	rsp, -8
	WORD    $0x8548; BYTE $0xd2 // TESTQ DX, DX                         // test	rdx, rdx
	JE      LBB1_5              // <--                                  // je	.LBB1_5
	CMPQ    DX, $0x1            // <--                                  // cmp	rdx, 1
	JNE     LBB1_6              // <--                                  // jne	.LBB1_6
	XORL    AX, AX              // <--                                  // xor	eax, eax
	JMP     LBB1_3              // <--                                  // jmp	.LBB1_3

LBB1_6:
	MOVQ DX, R8    // <--                                  // mov	r8, rdx
	ANDQ $-0x2, R8 // <--                                  // and	r8, -2
	XORL AX, AX    // <--                                  // xor	eax, eax

LBB1_7:
	LONG $0x870c8b44         // MOVL 0(DI)(AX*4), R9                 // mov	r9d, dword ptr [rdi + 4*rax]
	WORD $0x2941; BYTE $0xc9 // SUBL CX, R9                          // sub	r9d, ecx
	LONG $0x090c8d43         // LEAL 0(R9)(R9*1), CX                 // lea	ecx, [r9 + r9]
	LONG $0x1ff9c141         // SARL $0x1f, R9                       // sar	r9d, 31
	XORL CX, R9              // <--                                  // xor	r9d, ecx
	LONG $0x860c8944         // MOVL R9, 0(SI)(AX*4)                 // mov	dword ptr [rsi + 4*rax], r9d
	LONG $0x04874c8b         // MOVL 0x4(DI)(AX*4), CX               // mov	ecx, dword ptr [rdi + 4*rax + 4]
	WORD $0x0c2b; BYTE $0x87 // SUBL 0(DI)(AX*4), CX                 // sub	ecx, dword ptr [rdi + 4*rax]
	LONG $0x090c8d44         // LEAL 0(CX)(CX*1), R9                 // lea	r9d, [rcx + rcx]
	WORD $0xf9c1; BYTE $0x1f // SARL $0x1f, CX                       // sar	ecx, 31
	XORL R9, CX              // <--                                  // xor	ecx, r9d
	LONG $0x04864c89         // MOVL CX, 0x4(SI)(AX*4)               // mov	dword ptr [rsi + 4*rax + 4], ecx
	LONG $0x04874c8b         // MOVL 0x4(DI)(AX*4), CX               // mov	ecx, dword ptr [rdi + 4*rax + 4]
	ADDQ $0x2, AX            // <--                                  // add	rax, 2
	CMPQ R8, AX              // <--                                  // cmp	r8, rax
	JNE  LBB1_7              // <--                                  // jne	.LBB1_7

LBB1_3:
	WORD $0xc2f6; BYTE $0x01 // TESTL $0x1, DL                       // test	dl, 1
	JE   LBB1_5              // <--                                  // je	.LBB1_5
	WORD $0x148b; BYTE $0x87 // MOVL 0(DI)(AX*4), DX                 // mov	edx, dword ptr [rdi + 4*rax]
	WORD $0xca29             // SUBL CX, DX                          // sub	edx, ecx
	WORD $0x0c8d; BYTE $0x12 // LEAL 0(DX)(DX*1), CX                 // lea	ecx, [rdx + rdx]
	WORD $0xfac1; BYTE $0x1f // SARL $0x1f, DX                       // sar	edx, 31
	XORL CX, DX              // <--                                  // xor	edx, ecx
	WORD $0x1489; BYTE $0x86 // MOVL DX, 0(SI)(AX*4)                 // mov	dword ptr [rsi + 4*rax], edx

LBB1_5:
	NOP // (skipped)                            // mov	rsp, rbp
	NOP // (skipped)                            // pop	rbp
	RET // <--                                  // ret

DATA LCPI2_0<>+0x00(SB)/4, $0x00000001
DATA LCPI2_0<>+0x04(SB)/4, $0x00000001
DATA LCPI2_0<>+0x08(SB)/4, $0x00000001
DATA LCPI2_0<>+0x0c(SB)/4, $0x00000001
GLOBL LCPI2_0<>(SB), (RODATA|NOPTR), $16

TEXT ·zigzag_decode_sse(SB), NOSPLIT, $0-24
	MOVQ in+0(FP), DI
	MOVQ out+8(FP), SI
	MOVQ N+16(FP), DX
	WORD $0x8548; BYTE $0xd2 // TESTQ DX, DX                         // test	rdx, rdx
	JE   LBB2_11             // <--                                  // je	.LBB2_11
	NOP                      // (skipped)                            // push	rbp
	NOP                      // (skipped)                            // mov	rbp, rsp
	NOP                      // (skipped)                            // and	rsp, -8
	CMPQ DX, $0x8            // <--                                  // cmp	rdx, 8
	WORD $0x930f; BYTE $0xc0 // SETAE AL                             // setae	al
	MOVQ SI, CX              // <--                                  // mov	rcx, rsi
	SUBQ DI, CX              // <--                                  // sub	rcx, rdi
	CMPQ CX, $0x20           // <--                                  // cmp	rcx, 32
	WORD $0x930f; BYTE $0xc1 // SETAE CL                             // setae	cl
	WORD $0xc884             // TESTL CL, AL                         // test	al, cl
	JNE  LBB2_7              // <--                                  // jne	.LBB2_7
	XORL AX, AX              // <--                                  // xor	eax, eax
	JMP  LBB2_3              // <--                                  // jmp	.LBB2_3

LBB2_7:
	MOVQ DX, AX            // <--                                  // mov	rax, rdx
	ANDQ $-0x8, AX         // <--                                  // and	rax, -8
	XORL CX, CX            // <--                                  // xor	ecx, ecx
	MOVO LCPI2_0<>(SB), X0 // <--                                  // movdqa	xmm0, xmmword ptr [rip + .LCPI2_0]

LBB2_8:
	LONG $0x0c6f0ff3; BYTE $0x8f   // MOVDQU 0(DI)(CX*4), X1               // movdqu	xmm1, xmmword ptr [rdi + 4*rcx]
	LONG $0x546f0ff3; WORD $0x108f // MOVDQU 0x10(DI)(CX*4), X2            // movdqu	xmm2, xmmword ptr [rdi + 4*rcx + 16]
	LONG $0xd96f0f66               // MOVDQA X1, X3                        // movdqa	xmm3, xmm1
	LONG $0xd3720f66; BYTE $0x01   // PSRLD $0x1, X3                       // psrld	xmm3, 1
	LONG $0xe26f0f66               // MOVDQA X2, X4                        // movdqa	xmm4, xmm2
	LONG $0xd4720f66; BYTE $0x01   // PSRLD $0x1, X4                       // psrld	xmm4, 1
	LONG $0xc8db0f66               // PAND X0, X1                          // pand	xmm1, xmm0
	LONG $0xd0db0f66               // PAND X0, X2                          // pand	xmm2, xmm0
	LONG $0xedef0f66               // PXOR X5, X5                          // pxor	xmm5, xmm5
	LONG $0xe9fa0f66               // PSUBD X1, X5                         // psubd	xmm5, xmm1
	LONG $0xebef0f66               // PXOR X3, X5                          // pxor	xmm5, xmm3
	LONG $0xc9ef0f66               // PXOR X1, X1                          // pxor	xmm1, xmm1
	LONG $0xcafa0f66               // PSUBD X2, X1                         // psubd	xmm1, xmm2
	LONG $0xccef0f66               // PXOR X4, X1                          // pxor	xmm1, xmm4
	LONG $0x2c7f0ff3; BYTE $0x8e   // MOVDQU X5, 0(SI)(CX*4)               // movdqu	xmmword ptr [rsi + 4*rcx], xmm5
	LONG $0x4c7f0ff3; WORD $0x108e // MOVDQU X1, 0x10(SI)(CX*4)            // movdqu	xmmword ptr [rsi + 4*rcx + 16], xmm1
	ADDQ $0x8, CX                  // <--                                  // add	rcx, 8
	CMPQ AX, CX                    // <--                                  // cmp	rax, rcx
	JNE  LBB2_8                    // <--                                  // jne	.LBB2_8
	CMPQ AX, DX                    // <--                                  // cmp	rax, rdx
	JE   LBB2_10                   // <--                                  // je	.LBB2_10

LBB2_3:
	MOVQ AX, CX              // <--                                  // mov	rcx, rax
	WORD $0xc2f6; BYTE $0x01 // TESTL $0x1, DL                       // test	dl, 1
	JE   LBB2_5              // <--                                  // je	.LBB2_5
	WORD $0x0c8b; BYTE $0x87 // MOVL 0(DI)(AX*4), CX                 // mov	ecx, dword ptr [rdi + 4*rax]
	WORD $0x8941; BYTE $0xc8 // MOVL CX, R8                          // mov	r8d, ecx
	WORD $0xd141; BYTE $0xe8 // SHRL $0x1, R8                        // shr	r8d
	WORD $0xe183; BYTE $0x01 // ANDL $0x1, CX                        // and	ecx, 1
	WORD $0xd9f7             // NEGL CX                              // neg	ecx
	XORL R8, CX              // <--                                  // xor	ecx, r8d
	WORD $0x0c89; BYTE $0x86 // MOVL CX, 0(SI)(AX*4)                 // mov	dword ptr [rsi + 4*rax], ecx
	MOVQ AX, CX              // <--                                  // mov	rcx, rax
	ORQ  $0x1, CX            // <--                                  // or	rcx, 1

LBB2_5:
	LEAQ -0x1(DX), R8 // <--                                  // lea	r8, [rdx - 1]
	CMPQ AX, R8       // <--                                  // cmp	rax, r8
	JE   LBB2_10      // <--                                  // je	.LBB2_10

LBB2_6:
	WORD $0x048b; BYTE $0x8f // MOVL 0(DI)(CX*4), AX                 // mov	eax, dword ptr [rdi + 4*rcx]
	WORD $0x8941; BYTE $0xc0 // MOVL AX, R8                          // mov	r8d, eax
	WORD $0xd141; BYTE $0xe8 // SHRL $0x1, R8                        // shr	r8d
	WORD $0xe083; BYTE $0x01 // ANDL $0x1, AX                        // and	eax, 1
	WORD $0xd8f7             // NEGL AX                              // neg	eax
	XORL R8, AX              // <--                                  // xor	eax, r8d
	WORD $0x0489; BYTE $0x8e // MOVL AX, 0(SI)(CX*4)                 // mov	dword ptr [rsi + 4*rcx], eax
	LONG $0x048f448b         // MOVL 0x4(DI)(CX*4), AX               // mov	eax, dword ptr [rdi + 4*rcx + 4]
	WORD $0x8941; BYTE $0xc0 // MOVL AX, R8                          // mov	r8d, eax
	WORD $0xd141; BYTE $0xe8 // SHRL $0x1, R8                        // shr	r8d
	WORD $0xe083; BYTE $0x01 // ANDL $0x1, AX                        // and	eax, 1
	WORD $0xd8f7             // NEGL AX                              // neg	eax
	XORL R8, AX              // <--                                  // xor	eax, r8d
	LONG $0x048e4489         // MOVL AX, 0x4(SI)(CX*4)               // mov	dword ptr [rsi + 4*rcx + 4], eax
	ADDQ $0x2, CX            // <--                                  // add	rcx, 2
	CMPQ DX, CX              // <--                                  // cmp	rdx, rcx
	JNE  LBB2_6              // <--                                  // jne	.LBB2_6

LBB2_10:
	NOP // (skipped)                            // mov	rsp, rbp
	NOP // (skipped)                            // pop	rbp

LBB2_11:
	RET // <--                                  // ret

TEXT ·zigzag_delta_decode_sse(SB), NOSPLIT, $0-28
	MOVQ    in+0(FP), DI
	MOVQ    out+8(FP), SI
	MOVQ    N+16(FP), DX
	MOVLQZX prev+24(FP), CX
	NOP                         // (skipped)                            // push	rbp
	NOP                         // (skipped)                            // mov	rbp, rsp
	NOP                         // (skipped)                            // and	rsp, -8
	WORD    $0x8548; BYTE $0xd2 // TESTQ DX, DX                         // test	rdx, rdx
	JE      LBB3_5              // <--                                  // je	.LBB3_5
	CMPQ    DX, $0x1            // <--                                  // cmp	rdx, 1
	JNE     LBB3_6              // <--                                  // jne	.LBB3_6
	XORL    AX, AX              // <--                                  // xor	eax, eax
	JMP     LBB3_3              // <--                                  // jmp	.LBB3_3

LBB3_6:
	MOVQ DX, R8    // <--                                  // mov	r8, rdx
	ANDQ $-0x2, R8 // <--                                  // and	r8, -2
	XORL AX, AX    // <--                                  // xor	eax, eax

LBB3_7:
	LONG $0x870c8b44         // MOVL 0(DI)(AX*4), R9                 // mov	r9d, dword ptr [rdi + 4*rax]
	WORD $0x8945; BYTE $0xca // MOVL R9, R10                         // mov	r10d, r9d
	WORD $0xd141; BYTE $0xea // SHRL $0x1, R10                       // shr	r10d
	LONG $0x01e18341         // ANDL $0x1, R9                        // and	r9d, 1
	WORD $0xf741; BYTE $0xd9 // NEGL R9                              // neg	r9d
	XORL R10, R9             // <--                                  // xor	r9d, r10d
	WORD $0x0141; BYTE $0xc9 // ADDL CX, R9                          // add	r9d, ecx
	LONG $0x860c8944         // MOVL R9, 0(SI)(AX*4)                 // mov	dword ptr [rsi + 4*rax], r9d
	LONG $0x04874c8b         // MOVL 0x4(DI)(AX*4), CX               // mov	ecx, dword ptr [rdi + 4*rax + 4]
	WORD $0x8941; BYTE $0xca // MOVL CX, R10                         // mov	r10d, ecx
	WORD $0xd141; BYTE $0xea // SHRL $0x1, R10                       // shr	r10d
	WORD $0xe183; BYTE $0x01 // ANDL $0x1, CX                        // and	ecx, 1
	WORD $0xd9f7             // NEGL CX                              // neg	ecx
	XORL R10, CX             // <--                                  // xor	ecx, r10d
	WORD $0x0144; BYTE $0xc9 // ADDL R9, CX                          // add	ecx, r9d
	LONG $0x04864c89         // MOVL CX, 0x4(SI)(AX*4)               // mov	dword ptr [rsi + 4*rax + 4], ecx
	ADDQ $0x2, AX            // <--                                  // add	rax, 2
	CMPQ R8, AX              // <--                                  // cmp	r8, rax
	JNE  LBB3_7              // <--                                  // jne	.LBB3_7

LBB3_3:
	WORD $0xc2f6; BYTE $0x01 // TESTL $0x1, DL                       // test	dl, 1
	JE   LBB3_5              // <--                                  // je	.LBB3_5
	WORD $0x148b; BYTE $0x87 // MOVL 0(DI)(AX*4), DX                 // mov	edx, dword ptr [rdi + 4*rax]
	WORD $0xd789             // MOVL DX, DI                          // mov	edi, edx
	WORD $0xefd1             // SHRL $0x1, DI                        // shr	edi
	WORD $0xe283; BYTE $0x01 // ANDL $0x1, DX                        // and	edx, 1
	WORD $0xdaf7             // NEGL DX                              // neg	edx
	XORL DI, DX              // <--                                  // xor	edx, edi
	WORD $0xca01             // ADDL CX, DX                          // add	edx, ecx
	WORD $0x1489; BYTE $0x86 // MOVL DX, 0(SI)(AX*4)                 // mov	dword ptr [rsi + 4*rax], edx

LBB3_5:
	NOP // (skipped)                            // mov	rsp, rbp
	NOP // (skipped)                            // pop	rbp
	RET // <--                                  // ret
