//go:build !noasm && amd64
// Code generated by gocc -- DO NOT EDIT.

package streamvbyte


//go:noescape
func zigzag_encode_sse(in *int32, out *uint32, sz int64)

//go:noescape
func zigzag_delta_encode_sse(in *int32, out *uint32, sz int64, prev int32)

//go:noescape
func zigzag_decode_sse(in *uint32, out *int32, sz int64)

//go:noescape
func zigzag_delta_decode_sse(in *uint32, out *int32, sz int64, prev int32)
