//go:build !noasm && arm64
// Code generated by gocc -- DO NOT EDIT.

package streamvbyte


//go:noescape
func zigzag_encode(in *int32, out *uint32, sz int)

//go:noescape
func zigzag_delta_encode(in *int32, out *uint32, sz int, prev int32)

//go:noescape
func zigzag_decode(in *uint32, out *int32, sz int)

//go:noescape
func zigzag_delta_decode(in *uint32, out *int32, sz int, prev int32)
